### PR TITLE
Fix handling of mising tvshowid (rework strm handling)

### PR DESCRIPTION
**Pull request by hawkeyexp**

### CODE REVIEW

**Comment by hawkeyexp** [comment]
I only noticed that image for next episode is not show on strm files without post play screen (on post play screen it is shown) but it works - have to do a look to fix the image problem.

**Comment by im85288** [comment]
Thanks, I haven't tested any of this for quite some time and am finding the next episode (not using strms at the moment) is not getting played correctly. Not sure if somethings up with the JSON api for playing an item..very strange. I'm sure your change is nothing to do with it by the way

**Comment by hawkeyexp** [comment]
I'm working on it and try to find the issue - but  next episode for normal content is working fine for me and art is shown.

**Comment by im85288** [comment]
It seems fine on my android kodi install, yet to test strms but will pull in the changes thanks

**Comment by hawkeyexp** [comment]
Great!

**Comment by im85288** [comment]
@hawkeyexp - I finally got round to testing this now that I use the netflix addon, but it does not work correctly for me.

When for example it get's the initial now playing info I get:

`Got details of now playing media{"id":1,"jsonrpc":"2.0","result":{"item":{"episode":-1,"genre":[],"label":"Better Call Saul - S01E06","playcount":0,"season":-1,"showtitle":"","tvshowid":-1,"type":"unknown"}}}`

As you can see in the above there is no season or episode and the type is unknown, in the code it expects the type to be episode and for there to be a season and episode. With the above though the season and episode can only be seen in the label (which given the above would fail with your check to get the tvshow as it has the "- S01E06" in it

Do you get something different? Are you comfortable with adapting the code to try to lookup when the type is unknown and the label contains the season/episode number?

**Pull request merged**
