### PR TITLE
Align the default dialog and add fanart

### PR DESCRIPTION
**Pull request by razzeee**
See https://github.com/im85288/service.nextup.notification/pull/8

### CODE REVIEW

**Comment by razzeee** [comment]
Use https://github.com/im85288/service.nextup.notification/pull/9/files?w=0 for review

**Comment by im85288** [comment]
Sorry didn't know you could update the previous one. Thanks :)

**Comment by razzeee** [comment]
No problem. Sorry, if that sounded harsh, just want to learn things and let others know some things ;)

**Comment by im85288** [comment]
No problem at all, I've always done it that way in the past but learnt a new lesson today. Cheers

**Pull request merged**
