### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by bigpanda666**
currentepisodeid = result[ "result" ][ "item" ][ "id" ]  is incorrect should be currentepisodeid = result[ "result" ][ "item" ][ "episode" ].

### CODE REVIEW

**Comment by im85288** [comment]
It was actually correct, what you seem to need is the episode number.

So currentepisodeid = result[ "result" ][ "item" ][ "id" ]
     currentepisodenumber = result[ "result" ][ "item" ][ "episode" ]

The changes you introduced would cause the "find next" method to fail. 

For example:

**Comment by im85288** [comment]
```
           u'tvshowid': 49,
            u'dateadded': u'2014-12-2604: 44: 15',
            u'episode': 16,
            u'rating': 7.1999998092651367,
            u'season': 5,
            u'lastplayed': u'',
            u'episodeid': 2146,
```

In the above the episode number is 16 (so 16th episode), but the unique episode id is 2146

I fixed this and checked it in, please test

**Comment by bigpanda666** [comment]
Thanks for your changes...

There is no field 'id' returned in the json query so

 currentepisodeid = result[ "result" ][ "item" ][ "id" ]  is generating an exception.

I have tested by commenting out the line in my kodi setup and that works. Since it doesn't exist here i believe the line can be removed

**Comment by im85288** [comment]
There is that field when I get the details, as I stated it messes up with the users who selected include watched. If we are going to just use the episode number that piece of code needs changed too.

Strange that you get no ID though..I'm presuming that is for strm files only

**Comment by im85288** [comment]
FYI this is what I get back

{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "item": {
            "episode": 10,
            "id": 2144,
            "label": "Frienemies",
            "playcount": 2,
            "season": 5,
            "showtitle": "Numb3rs",
            "tvshowid": 49,
            "type": "episode"
        }
    }
}

**Comment by im85288** [comment]
I pushed a change which should work for both formats..please check

**Comment by bigpanda666** [comment]
This is strange ...

12:00:10 T:6580  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Got details of playing media{"id":1,"jsonrpc":"2.0","result":{"item":{"episode":4,"label":"3:00 A.M.-4:00 A.M.","playcount":0,"season":1,"showtitle":"24","tvshowid":-1,"type":"episode"}}}

wait.. isn't this the issue with non emby scanned strm's - no episodeid. We still don't know why.. A problem for another day.

**Comment by im85288** [comment]
Yes exactly, I think the codes fine now though. Are you happy with it?

**Comment by bigpanda666** [comment]
Just finished testing on windows and fire tv.. looks good to me

**Pull request merged**
